# Generated by Django 3.1.1 on 2020-10-03 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('cpf', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('dt_nascimento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('carga_horaria', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('cnpj', models.AutoField(primary_key=True, serialize=False)),
                ('nome_escola', models.CharField(max_length=200)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('cpf_resp', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('dt_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('cod_turma', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('turno', models.CharField(max_length=10)),
                ('cpnj_escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.escola')),
            ],
        ),
        migrations.CreateModel(
            name='Situacao_aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(null=True)),
                ('frequencia', models.IntegerField(null=True)),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.aluno')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('cpf_professor', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('salario', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='cod_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.turma'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='cpf_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.professor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cod_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.turma'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='cpf_resp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.responsavel'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
