# Generated by Django 3.1.1 on 2020-10-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_auto_20201002_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao_aluno',
            name='nota',
            field=models.FloatField(null=True),
        ),
    ]
