# Generated by Django 3.0.7 on 2020-10-12 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_auto_20201012_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao_aluno',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Disciplina'),
        ),
    ]
