# Generated by Django 3.0.7 on 2020-10-12 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_auto_20201012_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacao_aluno',
            name='cpf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.Aluno'),
        ),
    ]
